name: Tests

on:
  push:
    branches: [ QA_Branch ]
  pull_request:
    branches: [ QA_Branch ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: lironavon/docker-puppeteer-container:14.16.0
    env:
      CI: true
    steps:
    - name: install dependencies
      run: npm ci --ignore-scripts

    - name: test
      run: npm test