name: jsdoc

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
    - run: npm ci
    - run: npm install --save-dev jsdoc
    - run: jsdoc --ext .js './source/*'
