name: jsdoc

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./source
        recurse: true
        output_dir: jsdoc