name: jsdoc

on: [pull request]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm install --save-dev jsdoc
    - run: npx jsdoc -r source
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ./out # The folder the action should deploy.
