name: Lint

on: [pull_request]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mrdivyansh/eslint-action@1.0.7
        # GITHUB_TOKEN in forked repositories is read-only
        # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }} 
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          eslint-rc: .eslintrc.js
          execute-on-files:
            - ./source

    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
      # - uses: reviewdog/action-eslint@v1
      #   with:
      #     reporter: github-pr-review # Change reporter.
      #     eslint_flags: './source'

# jobs:
#   eslint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: stefanoeb/eslint-action@1.0.2
#         with:
#           files: source/