# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # - name: Test & publish code coverage
    #   uses: paambaati/codeclimate-action@v3.0.0
    #   env:
    #     CC_TEST_REPORTER_ID: 3746b129ff15217845a5a0646ba5168ba35b84682b2edb34d65297554161acc2
    #   with:
    #     coverageCommand: npm run coverage
    #     debug: true
    - run: npm ci
    - run: npm install eslint --save-dev
    - run: npm install eslint-plugin-only-warn --save-dev
    - run: npx eslint . --ext .js
  coverage:
    needs: [ build ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: npm install -g yarn
    - run: yarn install
    - uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 3746b129ff15217845a5a0646ba5168ba35b84682b2edb34d65297554161acc2
      with:
        coverageCommand: yarn run coverage
        debug: true
    - run: npm run build --if-present
    - run: npm test
    
